name: Cov+MDM_OR

paradigms:
  - LeftRightImagery
  - MotorImagery

citations:
  - https://doi.org/10.1109/NER49283.2021.9441279
  - https://citeseerx.ist.psu.edu/doc/10.1.1.713.5131

pipeline:
  - name: Covariances
    from: pyriemann.estimation
    parameters:
      estimator: oas

  - name: MDM
    from: pyriemann.classification
    metric: "riemann_or"
