name: TS+LR_OR

paradigms:
  - LeftRightImagery
  - MotorImagery

citations:
  - https://doi.org/10.1016/j.neucom.2012.12.039

pipeline:
  - name: Covariances
    from: pyriemann.estimation
    parameters:
      estimator: oas

  - name: TangentSpace
    from: pyriemann.tangentspace
    parameters:
      metric: "riemann_or"

  - name: LogisticRegression
    from: sklearn.linear_model
    parameters:
      C: 1.0
