name: XdawnCovariances + TS + LDA

paradigms:
  - LeftRightImagery
  - MotorImagery

citations:
  - https://doi.org/10.1016/j.neucom.2012.12.039

pipeline:
  - name: XdawnCovariances
    from: pyriemann.estimation
    parameters:
      estimator: oas
      xdawn_estimator: scm

  - name: TangentSpace
    from: pyriemann.tangentspace
    parameters:
      metric: "riemann"

  - name: LinearDiscriminantAnalysis
    from: sklearn.discriminant_analysis
