name: MF

paradigms:
  - LeftRightImagery
  - MotorImagery

pipeline:
  - name: Covariances
    from: pyriemann.estimation
    parameters:
      estimator: oas

  - name: MeanField
    from: enchanced_mdm_mf
    parameters:
      remove_outliers: False
      
      
